version: "3.7"
volumes:
  db-data:
networks:
  rescue_tracks:
services:
  rescue_tracks_frontend:
    image: rescue_tracks_frontend:latest
    build:
      context: ../rescue-tracks-frontend
    depends_on:
      - rescue_tracks
    ports:
      - "4200:4200"
    stop_grace_period: 10s
    networks:
      rescue_tracks:
        aliases:
          - frontend

  rescue_tracks:
    image: rescue_tracks_server:latest
    build:
      context: .
    depends_on:
      - database
    ports:
      - "9000:9000"
      - "9229:9229"
    stop_grace_period: 10s
    networks:
      rescue_tracks:
        aliases:
          - server

  database:
    image: postgres:9
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5439:5432"
    restart: "always"
    networks:
      rescue_tracks:
        aliases:
          - db
